version: "3"

services:
  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    build: ../Dummy.Api
    links:
      - rabbitmq
      - mongo
    ports:
      - '5000:5000'

  activities-service:
    build: ../Dummy.Service.Activities
    links:
      - rabbitmq
      - mongo
    ports:
      - '5050:5050'

  identity-service:
    build: ../Dummy.Service.Identity
    links:
      - rabbitmq
      - mongo
    ports:
      - '5051:5051'

  mongo:
    image: mongo
    volumes:
      - ../data/db:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.6.5-management
    ports: 
        - "15672:15672"
        - "5672:5672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5